config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index' # This should be used when user comes to us without embedding in Shopify

  mount ShopifyApp::Engine, at: '/'

# POST /:question_id/answers Create
# GET /:question_id/answers Index

  resources :products, only: [] do # No need for routes related to products
    resources :questions, only: [:index, :create]
  end

  namespace :admin do
    root to: 'dashboards#show'
    resources :questions, except: [:new, :create] do
      resources :answers, except: [:new]
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question, counter_cache: true
  belongs_to :shop

  validates :body, presence: true, length: { minimum: 16 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :questions
  belongs_to :shop

  validate :atleast_one_identifier_present

  private

  def atleast_one_identifier_present
    if self.shopify_id.blank?
      errors.add(:email, "can not be blank") if self.email.blank?
      errors.add(:name,  "can not be blank") if self.name.blank?
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :shop

  has_many :questions
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :product
  belongs_to :shop
  belongs_to :asker, class_name: "Customer"

  has_many :answers

  scope :new_first,   -> { order("id DESC") }
  scope :published,   -> { where(published: true) }

  validates :body, presence: true, length: { in: 16..256 }
end

app/models/shop.rb
class Shop < ApplicationRecord
  include ShopifyApp::SessionStorage

  has_many :products
  has_many :questions
  has_many :customers
end

app/controllers/admin/answers_controller.rb
module Admin
  class AnswersController < BaseController
    before_action :get_question

    def create
      @answer = @question.answers.build(answer_params)
      @answer.shop_id = @question.shop_id
      @shopify_product = ShopifyAPI::Product.find(@question.product.shopify_id)

      if @answer.save
        flash[:notice] = "Answer saved successfully!"
        redirect_to admin_question_url(@question)
      else
        flash[:error] = "Something went wrong saving the answer. Please correct the errors and try again."
        render "admin/questions/show"
      end
    end

    def edit
      @answer = @question.answers.find(params[:id])
    end

    def update
      @answer = @question.answers.find(params[:id])
      if @answer.update_attributes(answer_params)
        flash[:notice] = "Answer saved successfully!"
        redirect_to admin_question_url(@question)
      else
        flash[:error] = "Something went wrong saving the answer. Please correct the errors and try again."
        render :edit
      end
    end

    def destroy
      @answer = @question.answers.find(params[:id])

      if @answer.destroy
        flash[:notice] = "Answer deleted successfully!"
      else
        flash[:error] = "Something went wrong deleting the answer. Please correct the errors and try again."
      end

      redirect_to admin_question_url(@question)
    end

    private

    def get_question
      @question = current_shop.questions.find(params[:question_id])
    end

    def answer_params
      params.require(:answer).permit(:body)
    end
  end
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ShopifyApp::AuthenticatedController
    helper ApplicationHelper

    helper_method :current_shop
    before_action :shop_required

    private

    def current_shop
      @current_shop ||= Shop.find_by_shopify_domain(@shop_session.shop.domain)
    end

    def shop_required
      # In case someone tries to access application not being embedded in shopify admin.
      # Ask them to access it over shopify admin.
    end
  end
end

app/controllers/admin/dashboards_controller.rb
module Admin
  class DashboardsController < BaseController
    def show
      redirect_to admin_questions_url(published: false)
    end
  end
end

app/controllers/admin/questions_controller.rb
module Admin
  class QuestionsController < BaseController
    before_action :get_question, only: [:show, :update]

    def show
      @shopify_product = ShopifyAPI::Product.find(@question.product.shopify_id)
      @answer = @question.answers.build
    end

    def index
      if params[:published] == 'all'
        @questions = current_shop.questions.page(params[:page])

      else
        @questions = current_shop.questions.where(published: params[:published]).page(params[:page])
      end
    end

    def update
      @question.toggle!(:published)
      redirect_to admin_question_url(@question.id)
    end

    private

    def get_question
      @question = current_shop.questions.find(params[:id])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ShopifyApp::AuthenticatedController
  def index
    @products = ShopifyAPI::Product.find(:all, params: { limit: 10 })
    @webhooks = ShopifyAPI::Webhook.find(:all)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  if Rails.env != 'test'
    include ShopifyApp::AppProxyVerification
  end

  before_action :get_shop, :get_product
  before_action :get_customer, only: [:create]

  def create
    if @product.blank?
      @product = @shop.products.build(shopify_id: params[:product_id])
      unless @product.save
        respond_to do |format|
          # Something went wrong saving the product
          format.json { render(json: { error: "product did not save" }, status: :internal_server_error) }
        end
        return
      end
    end

    if @customer.blank?
      @customer = @shop.customers.build(shopify_id: params[:customer][:shopify_id], name: params[:customer][:name], email: params[:customer][:email])
      unless @customer.save
        respond_to do |format|
          # Customer is invalid. Tell the client what is invalid about it.
          format.json { render(json: { error: "customer creation failed" }, status: :bad_request) }
        end
        return
      end
    end

    @question = @product.questions.build(body: params[:body], shop: @shop, asker: @customer)
    if @question.save
      respond_to do |format|
        format.json { render("questions/show") }
      end

    else
      respond_to do |format|
        # Question is invalid. Tell the client what is invalid about it.
        format.json { render(json: { error: "question creation failed" }, status: :bad_request) }
      end
    end
  end

  def index
    if @product.blank?
      respond_to do |format|
        format.json { render(json: { error: "product does not exist" }, status: :not_found) }
      end
      return
    end

    @questions = @product.questions.published.page(params[:page]).per(4)
    respond_to do |format|
      format.json
    end
  end

  private

  def get_shop
    @shop = Shop.find_by_shopify_domain(params[:shop])
    unless @shop
      respond_to do |format|
        format.json { render(json: { error: "shop not found" }, status: :unauthorized) }
      end
      return
    end
  end

  def get_product
    @product = @shop.products.find_by_shopify_id(params[:product_id])
  end

  def get_customer
    if params[:customer][:shopify_id].present?
      @customer = @shop.customers.find_by_shopify_id(params[:customer][:shopify_id])

    elsif params[:customer][:email].present?
      @customer = @shop.customers.find_by_email(params[:customer][:email])

    else
      respond_to do |format|
        format.json { render(json: { error: "email can not be blank" }, status: :unauthorized) }
      end
      return
    end
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def yes_or_no(bool)
    return "Yes" if bool
    return "No"
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/admin/answers/edit.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({ title: "Editing Answer" });
    });
  </script>
<% end %>

<h2>Editing Answer# <%= @answer.id %></h2>

<div class="answer-form-container">
  <div class="well well-lg">
    <span><%= link_to("View", admin_question_path(@answer.question.id)) %>:
    <%= @answer.question.body %>
  </div>

  <%= form_for([:admin, @answer.question, @answer]) do |f| %>
    <% if @answer.errors.any? %>
      <ul class="answer-errors">
        <% @answer.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="form-group">
      <%= f.text_area :body, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit class: "form-control" %>
    </div>
  <% end %>
</div>

app/views/admin/questions/index.html.erb
<table class="table table-bordered table-condensed table-striped">
  <thead>
    <th>ID</th>
    <th>Question</th>
    <th>Published</th>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td>
          <%= link_to(question.id, admin_question_path(question.id)) %>
        </td>
        <td>
          <%= question.body %>
        </td>
        <td>
          <%= yes_or_no(question.published) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate(@questions) %>

app/views/admin/questions/show.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({ title: "Question" });
    });
  </script>
<% end %>

<h2>Displaying Question# <%= @question.id %></h2>

<div class="question-container">
  <div class="product-container well well-sm">
    <span><strong>Product:</strong> <%= link_to @shopify_product.title, "https://#{@shop_session.url}/admin/products/#{@shopify_product.id}", target: "_top" %></span>
  </div>

  <div class="question-body well well-lg">
    <p class="lead">
      <%= @question.body %>
    </p>

    <div class="email">
      <%= @question.asker.email %>
    </div>

    <div class="name">
      <%= @question.asker.name %>
    </div>

    <% if @question.asker.shopify_id %>
      <div class="shopify-url">
        <%= link_to(@question.asker.shopify_id, "https://#{@shop_session.url}/admin/customers/#{@question.asker.shopify_id}", target: "_top") %>
      </div>
    <% end %>
  </div>

  <div class="answers-container">
    A total of <strong><%= @question.answers_count %></strong> answers.

    <table class="table table-bordered table-condensed table-striped">
      <thead>
        <th>Answer</th>
        <th>Actions</th>
      </thead>
      <tbody>
        <% @question.answers.each do |answer| %>
          <% if answer.persisted? %>
            <tr>
              <td><%= answer.body %></td>
              <td>
                <%= link_to("Edit", edit_admin_question_answer_path(@question, answer)) %> |
                <%= link_to("Delete", admin_question_answer_path(@question, answer), method: :delete) %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="answer-form-container">
    Answer this question:
    <%= form_for([:admin, @question, @answer]) do |f| %>
      <% if @answer.errors.any? %>
        <ul class="answer-errors">
          <% @answer.errors.full_messages.each do |error| %>
            <li><%= error %></li>
          <% end %>
        </ul>
      <% end %>
      <div class="form-group">
        <%= f.text_area :body, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.submit class: "form-control" %>
      </div>
    <% end %>
  </div>

  <div class="well well-sm">
    <%= link_to((@question.published? ? "Unpublish this question from Store" : "Publish this question to Store"), admin_question_path(@question), method: :put) %>
  </div>
</div>

app/views/home/index.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({ title: "Dashboard" });
    });
  </script>
<% end %>
<h2>Products</h2>

<ul>
  <% @products.each do |product| %>
    <li><%= link_to product.title, "https://#{@shop_session.url}/admin/products/#{product.id}", target: "_top" %></li>
  <% end %>
</ul>

<hr>

<h2>Webhooks</h2>

<% if @webhooks.present? %>
  <ul>
    <% @webhooks.each do |webhook| %>
      <li><%= webhook.topic %> : <%= webhook.address %></li>
    <% end %>
  </ul>
<% else %>
  <p>This app has not created any webhooks for this Shop. Add webhooks to your ShopifyApp initializer if you need webhooks</p>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
<script type="text/javascript">
  var eventName = typeof(Turbolinks) !== 'undefined' ? 'page:change' : 'DOMContentLoaded';

  document.addEventListener(eventName, function() {
    <% if flash[:notice] %>
      ShopifyApp.flashNotice("<%= j flash[:notice].html_safe %>");
    <% end %>

    <% if flash[:error] %>
      ShopifyApp.flashError("<%= j flash[:error].html_safe %>");
    <% end %>
  });
</script>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar-header">
  <%= link_to("Dashboard", admin_root_path, class: 'navbar-brand') %>
  <ul class="nav navbar-nav">
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Questions <span class="caret"></span>
      </a>
      <ul class="dropdown-menu" role="menu">
        <li>
          <%= link_to("Unpublished", admin_questions_path(published: false)) %>
        </li>
        <li>
          <%= link_to("Published", admin_questions_path(published: true)) %>
        </li>
        <li>
          <%= link_to("All", admin_questions_path(published: 'all')) %>
        </li>
      </ul>
    </li>
  </ul>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Owl</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <% application_name = ShopifyApp.configuration.application_name %>
    <title><%= application_name %></title>
    <%= stylesheet_link_tag 'application', media: "all" %>
    <%= javascript_include_tag 'application', "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <%= render(partial: 'layouts/navigation') %>
    </nav>

    <div class="row-fluid">
      <div class="span3">&nbsp;</div>

      <div class="span6">
        <div class="content">
          <div class="row">
            <%= yield %>
          </div>
        </div>
      </div>

      <div class="span3">&nbsp;</div>
    </div>

    <%= render 'layouts/flash_messages' %>

    <script src="https://cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>

    <script type="text/javascript">
      ShopifyApp.init({
        apiKey: "<%= ShopifyApp.configuration.api_key %>",
        shopOrigin: "<%= "https://#{ @shop_session.url }" if @shop_session %>",
        debug: <%= ['development'].include?(Rails.env) %>,
        forceRedirect: <%= ['test'].exclude?(Rails.env) %>
      });
    </script>

    <% if content_for?(:javascript) %>
      <div id="ContentForJavascript" data-turbolinks-temporary>
        <%= yield :javascript %>
      </div>
    <% end %>
  </body>
</html>